services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iscan_frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://scan-api.ristart.kz
    restart: unless-stopped
    networks:
      - frontend_network

networks:
  frontend_network:
    driver: bridge
