version: '3.8'

services:
  frontend:
    build:
      context: ./iscan-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      # Remove volumes for production, but keep for development if needed
      - ./iscan-frontend:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    networks:
      - iscan_network

networks:
  iscan_network:
    name: iscan_shared_network
    external: true
