version: '3.8'

services:
  frontend:
    build: ./iscan-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    volumes:
      - ./iscan-frontend:/app
      - /app/node_modules
    networks:
      - iscan_network

networks:
  iscan_network:
    name: iscan_shared_network
    external: true
