version: '3.8'

services:
  frontend:
    build:
      context: ./iscan-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
    # No volumes for production - everything is built into the image
    restart: unless-stopped
    networks:
      - iscan_network

networks:
  iscan_network:
    name: iscan_shared_network
    external: true
